AVFD_Parameters = {
	'Read N5 From File' 		:	0.00	,
	'Read EM Field From File'	:	1.00	,
	'Print Number Density'		:	0.00	,
	'Axial Charge Damping'		:	0.00	,
	'B Field Strength'			:	0.00	,
	'B Field LifeTime'			:	0.8	,
	'Vector Relaxation Time'	:	0.50	,
	'Axial Relaxation Time'		:	0.50	,
	'Vector Conductivity'		:	0.10	,
	'Axial Conductivity'		:	0.10	,
	'u Vector Charge'			:	0.00	,
	'd Vector Charge'			:	0.00	,
	's Vector Charge'			:	0.00	,
	'u Axial Charge'			:	0.0	,
	'd Axial Charge'			:	0.0	,
	's Axial Charge'			:	0.0	,
	'u Vector Current'			:	0.00	,
	'd Vector Current'			:	0.00	,
	's Vector Current'			:	0.00	,
	'u Axial Current'			:	0.00	,
	'd Axial Current'			:	0.00	,
	's Axial Current'			:	0.00	,
	'u Vector 1st Eccentricity'	: 	0.00	,
	'd Vector 1st Eccentricity'	: 	0.00	,
	's Vector 1st Eccentricity'	: 	0.00	,
	'u Vector 2nd Eccentricity'	: 	0.00	,
	'd Vector 2nd Eccentricity'	: 	0.00	,
	's Vector 2nd Eccentricity'	: 	0.00	,
	'u Axial 1st Eccentricity'	: 	0.00	,
	'd Axial 1st Eccentricity'	: 	0.00	,
	's Axial 1st Eccentricity'	: 	0.00	,
	'u Axial 2nd Eccentricity'	: 	0.00	,
	'd Axial 2nd Eccentricity'	: 	0.00	,
	's Axial 2nd Eccentricity'	: 	0.00	,
}
